from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(857, 417)
        MainWindow.setMouseTracking(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 210, 841, 201))
        self.groupBox_2.setObjectName("groupBox_2")
        self.bEjecutar = QtWidgets.QPushButton(self.groupBox_2)
        self.bEjecutar.setGeometry(QtCore.QRect(650, 40, 91, 31))
        self.bEjecutar.setObjectName("bEjecutar")
        self.boxGrafo_2 = QtWidgets.QComboBox(self.groupBox_2)
        self.boxGrafo_2.setGeometry(QtCore.QRect(460, 40, 161, 31))
        self.boxGrafo_2.setObjectName("boxGrafo_2")
        self.boxGrafo_2.addItem("")
        self.boxGrafo_1 = QtWidgets.QComboBox(self.groupBox_2)
        self.boxGrafo_1.setGeometry(QtCore.QRect(300, 40, 131, 31))
        self.boxGrafo_1.setObjectName("boxGrafo_1")
        self.boxGrafo_1.addItem("")
        self.boxOpcion = QtWidgets.QComboBox(self.groupBox_2)
        self.boxOpcion.setGeometry(QtCore.QRect(10, 40, 261, 31))
        self.boxOpcion.setObjectName("boxOpcion")
        self.boxOpcion.addItem("")
        self.boxOpcion.addItem("")
        self.boxOpcion.addItem("")
        self.boxOpcion.addItem("")
        self.boxOpcion.addItem("")
        self.boxOpcion.addItem("")
        self.boxOpcion.addItem("")
        self.labeIsomorfo = QtWidgets.QLabel(self.groupBox_2)
        self.labeIsomorfo.setGeometry(QtCore.QRect(460, 20, 171, 16))
        self.labeIsomorfo.setObjectName("labeIsomorfo")
        self.bEliminar = QtWidgets.QPushButton(self.groupBox_2)
        self.bEliminar.setGeometry(QtCore.QRect(670, 160, 161, 28))
        self.bEliminar.setObjectName("bEliminar")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 841, 181))
        self.groupBox.setObjectName("groupBox")
        self.labelVertices = QtWidgets.QLabel(self.groupBox)
        self.labelVertices.setGeometry(QtCore.QRect(10, 40, 261, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelVertices.setFont(font)
        self.labelVertices.setObjectName("labelVertices")
        self.lineArista = QtWidgets.QLineEdit(self.groupBox)
        self.lineArista.setGeometry(QtCore.QRect(270, 80, 411, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineArista.setFont(font)
        self.lineArista.setText("")
        self.lineArista.setObjectName("lineArista")
        self.labelAristas = QtWidgets.QLabel(self.groupBox)
        self.labelAristas.setGeometry(QtCore.QRect(10, 90, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelAristas.setFont(font)
        self.labelAristas.setObjectName("labelAristas")
        self.lineVertice = QtWidgets.QLineEdit(self.groupBox)
        self.lineVertice.setGeometry(QtCore.QRect(270, 30, 411, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineVertice.setFont(font)
        self.lineVertice.setText("")
        self.lineVertice.setObjectName("lineVertice")
        self.bCreargrafo = QtWidgets.QPushButton(self.groupBox)
        self.bCreargrafo.setGeometry(QtCore.QRect(690, 50, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bCreargrafo.setFont(font)
        self.bCreargrafo.setObjectName("bCreargrafo")
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionCrear_grafo = QtWidgets.QAction(MainWindow)
        self.actionCrear_grafo.setObjectName("actionCrear_grafo")
        self.actionBorrar_todos_los_grafos = QtWidgets.QAction(MainWindow)
        self.actionBorrar_todos_los_grafos.setObjectName("actionBorrar_todos_los_grafos")
        self.actionSalir = QtWidgets.QAction(MainWindow)
        self.actionSalir.setObjectName("actionSalir")
        self.actionasd = QtWidgets.QAction(MainWindow)
        self.actionasd.setObjectName("actionasd")
        self.actionverificar_caminos = QtWidgets.QAction(MainWindow)
        self.actionverificar_caminos.setObjectName("actionverificar_caminos")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Interaccion con grafos creados"))
        self.bEjecutar.setText(_translate("MainWindow", "Ejecutar"))
        self.boxGrafo_2.setItemText(0, _translate("MainWindow", "Elija un segundo grafo"))
        self.boxGrafo_1.setItemText(0, _translate("MainWindow", "Elija un grafo"))
        self.boxOpcion.setItemText(0, _translate("MainWindow", "Elija una opcion"))
        self.boxOpcion.setItemText(1, _translate("MainWindow", "1) Mostrar matriz de adyacendia"))
        self.boxOpcion.setItemText(2, _translate("MainWindow", "2) Imprimir cantidad de vertices y aristas"))
        self.boxOpcion.setItemText(3, _translate("MainWindow", "3) Verificar si es convexo o no"))
        self.boxOpcion.setItemText(4, _translate("MainWindow", "4) Caminos"))
        self.boxOpcion.setItemText(5, _translate("MainWindow", "6) Isomorfismo"))
        self.boxOpcion.setItemText(6, _translate("MainWindow", "5) Numero cromatico y coloreo"))
        self.labeIsomorfo.setText(_translate("MainWindow", "Solo en caso de isomorfismo"))
        self.bEliminar.setText(_translate("MainWindow", "Eliminar todos los grafos"))
        self.groupBox.setTitle(_translate("MainWindow", "Creacion de grafos"))
        self.labelVertices.setText(_translate("MainWindow", "Ingrese vertices separados por espacio"))
        self.labelAristas.setText(_translate("MainWindow", "Ingrese aristas Ej: a,b b,c c,a"))
        self.bCreargrafo.setText(_translate("MainWindow", "Crear grafo"))
        self.actionCrear_grafo.setText(_translate("MainWindow", "Ingresar grafo"))
        self.actionBorrar_todos_los_grafos.setText(_translate("MainWindow", "Borrar todos los grafos"))
        self.actionSalir.setText(_translate("MainWindow", "Salir"))
        self.actionasd.setText(_translate("MainWindow", "asd"))
        self.actionverificar_caminos.setText(_translate("MainWindow", "verificar caminos"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
